export const ar = {
  // General
  'sales_tracker_pro': 'نظام تتبع المبيعات',
  'login': 'تسجيل الدخول',
  'logout': 'تسجيل الخروج',
  'username': 'اسم المستخدم',
  'password': 'كلمة المرور',
  'dashboard': 'لوحة التحكم',
  'add_visit': 'إضافة زيارة',
  'reports': 'التقارير',
  'admin_panel': 'لوحة الإدارة',
  'submit': 'إرسال',
  'cancel': 'إلغاء',
  'loading': 'جاري التحميل...',
  'error': 'خطأ',
  
  // Login Page
  'login_title': 'مرحباً بك في نظام تتبع المبيعات',
  'login_subtitle': 'قم بتسجيل الدخول للوصول إلى لوحة التحكم الخاصة بك',
  'invalid_credentials': 'اسم المستخدم أو كلمة المرور غير صحيحة',

  // Data Entry Page
  'new_visit_report': 'تقرير زيارة جديد',
  'rep_name': 'اسم المندوب',
  'visit_date': 'تاريخ الزيارة',
  'client_name': 'اسم العميل',
  'employee_name': 'اسم الموظف',
  'employee_phone': 'رقم هاتف الموظف',
  'company_email': 'ايميل الشركة',
  'client_location': 'موقع العميل',
  'get_current_location': 'الحصول على الموقع الحالي',
  'fetching_location': 'جاري تحديد الموقع...',
  'location_error': 'تعذر الحصول على الموقع. يرجى التأكد من تفعيل أذونات الموقع.',
  'location_success': 'تم تحديد الموقع بنجاح',
  'latitude': 'خط العرض',
  'longitude': 'خط الطول',
  'client_type': 'نوع العميل',
  'new': 'جديد',
  'old': 'قديم',
  'purpose_of_visit': 'الغرض من الزيارة',
  'open_account': 'فتح حساب للعميل',
  'follow_papers': 'متابعة اوراق العميل',
  'follow_payment': 'متابعة تحصيل',
  'follow_quotations': 'متابعة عروض',
  'delivery': 'توصيل طلبات',
  'renew_deal': 'تجديد التعامل',
  'review_invoice': 'مراجعة لفاتورة او صنف سابق',
  'follow_up': 'متابعة',
  'notes': 'ملاحظات',
  'visit_added_successfully': 'تمت إضافة الزيارة بنجاح!',
  'select_existing_client': 'اختر عميل حالي',
  'client_name_placeholder_old': 'اختر أو اكتب اسم العميل',

  // Dashboard Page
  'welcome_back': 'مرحباً بعودتك',
  'dashboard_overview': 'هنا نظرة عامة على أداء فريقك.',
  'total_visits': 'إجمالي الزيارات',
  'new_clients': 'عملاء جدد',
  'visits_by_rep': 'الزيارات حسب المندوب',
  'client_types_by_rep': 'أنواع العملاء حسب المندوب',
  'visit_purpose_distribution': 'توزيع أغراض الزيارات',
  'rep_performance_comparison': 'مقارنة أداء المندوبين',
  'filter_by_rep': 'تصفية حسب المندوب',
  'all_reps': 'كل المندوبين',
  'start_date': 'تاريخ البدء',
  'end_date': 'تاريخ الانتهاء',
  'visits_data': 'بيانات الزيارات',
  'search_placeholder': 'ابحث عن عميل, مندوب, ملاحظات...',

  // Admin Page
  'user_management': 'إدارة المستخدمين',
  'add_user': 'إضافة مستخدم',
  'user_list': 'قائمة المستخدمين',
  'name': 'الاسم',
  'role': 'الدور',
  'actions': 'الإجراءات',
  'admin': 'مدير',
  'rep': 'مندوب',
  'edit': 'تعديل',
  'delete': 'حذف',
  'feature_not_implemented': 'هذه الميزة للعرض فقط.',
  'edit_user': 'تعديل المستخدم',
  'save_changes': 'حفظ التغييرات',
  'user_role': 'دور المستخدم',
  'new_password': 'كلمة مرور جديدة (اتركه فارغاً لعدم التغيير)',
  'user_updated_successfully': 'تم تحديث المستخدم بنجاح!',
  'user_added_successfully': 'تمت إضافة المستخدم بنجاح!',
  'confirm_password': 'تأكيد كلمة المرور',
  'passwords_do_not_match': 'كلمتا المرور غير متطابقتين',
  'cannot_delete_yourself': 'لا يمكنك حذف حسابك بنفسك.',
  'confirm_delete_user': 'هل أنت متأكد أنك تريد حذف {user}؟ سيؤدي هذا أيضًا إلى حذف جميع الزيارات المرتبطة به.',
};