export const en = {
  // General
  'sales_tracker_pro': 'Sales Tracker Pro',
  'login': 'Login',
  'logout': 'Logout',
  'username': 'Username',
  'password': 'Password',
  'dashboard': 'Dashboard',
  'add_visit': 'Add Visit',
  'reports': 'Reports',
  'admin_panel': 'Admin Panel',
  'submit': 'Submit',
  'cancel': 'Cancel',
  'loading': 'Loading...',
  'error': 'Error',

  // Login Page
  'login_title': 'Welcome to Sales Tracker Pro',
  'login_subtitle': 'Sign in to access your dashboard',
  'invalid_credentials': 'Invalid username or password',

  // Data Entry Page
  'new_visit_report': 'New Visit Report',
  'rep_name': 'Representative Name',
  'visit_date': 'Visit Date',
  'client_name': 'Client Name',
  'employee_name': 'Employee Name',
  'employee_phone': 'Employee Phone Number',
  'company_email': 'Company Email',
  'client_location': 'Client Location',
  'get_current_location': 'Get Current Location',
  'fetching_location': 'Fetching location...',
  'location_error': 'Could not get location. Please ensure location permissions are enabled.',
  'location_success': 'Location captured successfully',
  'latitude': 'Latitude',
  'longitude': 'Longitude',
  'client_type': 'Client Type',
  'new': 'New',
  'old': 'Old',
  'purpose_of_visit': 'Purpose of Visit',
  'open_account': 'Opening a client account',
  'follow_papers': 'Follow-up on customer papers',
  'follow_payment': 'Follow-up on payment',
  'follow_quotations': 'Follow-up on quotations',
  'delivery': 'Delivery of orders',
  'renew_deal': 'Renew dealing with an old client',
  'review_invoice': 'Review of an invoice or previous item',
  'follow_up': 'Follow-up',
  'notes': 'Notes',
  'visit_added_successfully': 'Visit added successfully!',
  'select_existing_client': 'Select an existing client',
  'client_name_placeholder_old': 'Select or type a client name',


  // Dashboard Page
  'welcome_back': 'Welcome back',
  'dashboard_overview': 'Here is an overview of your team\'s performance.',
  'total_visits': 'Total Visits',
  'new_clients': 'New Clients',
  'visits_by_rep': 'Visits by Rep',
  'client_types_by_rep': 'Client Types by Rep',
  'visit_purpose_distribution': 'Visit Purpose Distribution',
  'rep_performance_comparison': 'Rep Performance Comparison',
  'filter_by_rep': 'Filter by Rep',
  'all_reps': 'All Representatives',
  'start_date': 'Start Date',
  'end_date': 'End Date',
  'visits_data': 'Visits Data',
  'search_placeholder': 'Search client, rep, notes...',

  // Admin Page
  'user_management': 'User Management',
  'add_user': 'Add User',
  'user_list': 'User List',
  'name': 'Name',
  'role': 'Role',
  'actions': 'Actions',
  'admin': 'Admin',
  'rep': 'Rep',
  'edit': 'Edit',
  'delete': 'Delete',
  'feature_not_implemented': 'This feature is for demonstration only.',
  'edit_user': 'Edit User',
  'save_changes': 'Save Changes',
  'user_role': 'User Role',
  'new_password': 'New Password (leave blank to keep unchanged)',
  'user_updated_successfully': 'User updated successfully!',
  'user_added_successfully': 'User added successfully!',
  'confirm_password': 'Confirm Password',
  'passwords_do_not_match': 'Passwords do not match',
  'cannot_delete_yourself': 'You cannot delete yourself.',
  'confirm_delete_user': 'Are you sure you want to delete {user}? This will also delete all associated visits.',
};